apiVersion: v1
kind: Service
metadata:
  name: api-course
  namespace: optimumtech
  labels:
    app: api-course
spec:
  selector:
    app: api-course
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
