apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: optimumtech
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: optimumtech
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
