apiVersion: v1
kind: Service
metadata:
  name: api-payment
  namespace: optimumtech
  labels:
    app: api-payment
spec:
  selector:
    app: api-payment
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
