name: OptimumTech CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/eva3-implementacion

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Build and test all services
        run: mvn clean verify

      - name: JaCoCo Coverage Report
        working-directory: ./api_course
        run: mvn jacoco:report

      - name: Snyk - Análisis de dependencias y seguridad
        run: |
          docker run --rm \
            -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
            -v "${{ github.workspace }}:/app" \
            snyk/snyk:maven-latest \
            test --severity-threshold=high --file=pom.xml

      - name: SonarQube - Análisis de calidad de código (Maven)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.token=${{ env.SONAR_TOKEN }}
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.organization=tbtha
          -Dsonar.qualitygate.wait=true

      - name: Build Docker image api_course
        working-directory: ./api_course
        run: docker build -t api_course .

      - name: Verify Docker Compose
        run: docker compose config
